import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lia | 감정에서 시작하는 폐경 케어",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" data-locale="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script id="locale-hydration" strategy="beforeInteractive" dangerouslySetInnerHTML={{ __html: '(()=>{const a=(l)=>{const r=document.documentElement;if(!r)return;r.setAttribute("lang",l);r.setAttribute("data-locale",l);};const n=(v)=>{if(!v)return null;const s=v.toLowerCase();return s==="ko"||s==="en"?s:null;};try{const p=new URLSearchParams(window.location.search);const q=n(p.get("lang"));if(q){a(q);return;}}catch{}const m=document.cookie.match(/(?:^|; )lang=([^;]*)/);if(m){const c=n(decodeURIComponent(m[1]));if(c){a(c);return;}}a("ko");})();' }} />
        {children}
      </body>
    </html>
  );
}
